disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - force_cast

opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
  - Openfield
  - OpenfieldTests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Openfield/R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 100
  error: 150

file_length:
  warning: 500
  error: 1200

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

trailing_comma:
  mandatory_comma: true

identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - Log
    - vc
    - db
