//
//  EventCategory.swift
//  Openfield
//
//  Created by Daniel Kochavi on 29/03/2020.
//  Copyright © 2020 Prospera. All rights reserved.
//

enum EventCategory {
    static let welcome = "welcome"
    static let login = "login"
    static let navigation = "navigation"
    static let imageViewer = "image_viewer"
    static let layersWalkthrough = "layers_walkthrough"
    static let keypad = "keypad"
    static let carousel = "carousel"
    static let introCarousel = "intro_carousel"
    static let loginPhone = "login_phone"
    static let countrySelection = "country_selection"
    static let loginCode = "login_code"
    static let impersonation = "impersonation"
    static let resendCode = "resend_code"
    static let feed = "feed"
    static let feedList = "feed_list"
    static let feedFilters = "feed_filters"
    static let imageryPopup = "imagery_popup"
    static let insight = "insight"
    static let locationInsight = "location_insight"
    static let monthlyReport = "monthly_report"
    static let insightCard = "insight_card"
    static let feedbackSheet = "feedback_sheet"
    static let analysis = "analysis"
    static let layerSelection = "layer_selection"
    static let detectionsSelection = "detections_selection"
    static let dateSelection = "date_selection"
    static let settings = "settings"
    static let settingsNotifications = "settings_notifications"
    static let settingsTeam = "settings_team"
    static let settingsHelp = "settings_help"
    static let settingsLogout = "settings_logout"
    static let fieldsList = "fields_list"
    static let highlights = "highlights"
    static let highlight = "highlight"
    static let rolePopUp = "role_popup"
    static let farmPopUp = "farm_popup"
    static let feeddbackWalkthoroughPopup = "feddback_walkthorough_popup"
    static let noConnection = "no_connection"
    static let cloudIndication = "cloud_indication"
    static let feedbackFreeText = "feedback_free_text"
    static let optionalUpdate = "optional_update"
    static let fieldsFilter = "fields_filter"
    static let fieldInsights = "field_insights"
    static let field = "field"
    static let locationIssues = "location_issues"
    static let notifications = "notifications"
    static let reportOverviewInfo = "report_overview_info"
    static let contract = "contract"
    static let localization = "localization"
    static let virtualScouting = "virtual_scouting"
}
